### ISSUE TITLE
Compatibility with Go 1.13

### ISSUE THREAD

**Issue by kamal2311** [MicahParks/compatibility-keyfunc#1]
I was looking for using keyfunc with Golang 1.13. Since this package depends on github.com/golang-jwt/jwt/v4 which itself requires Golang 1.15 I am unable to do so.

Any pointers on how may I achieve it?

**Comment by MicahParks** [comment]
I too used to be stuck on old versions of things at a previous job, so I have sympathy for this. I'll look into a solution for you.

**Comment by MicahParks** [comment]
I've removed `github.com/golang-jwt/jwt/v4` as a dependency and made `github.com/dgrijalva/jwt-go` the main dependency.

If you refresh your dependency by using `go get github.com/MicahParks/compatibility-keyfunc@v0.13.0`, you should have the latest version of this package that can run on Go 1.13.

Remember to use the `KeyfuncLegacy` or `KeyfuncF3T` methods of the [`keyfunc.JWKS`](https://pkg.go.dev/github.com/MicahParks/compatibility-keyfunc@v0.12.0#JWKS) data structure.

While I was at it, I updated this project to use the new changes from this PR: https://github.com/MicahParks/keyfunc/pull/25

Those changes should be on the main `keyfunc` project sometime early next week.

**Comment by MicahParks** [comment]
Let me know if you need additional help using this project!

**Comment by kamal2311** [comment]
Thank you, @MicahParks  for such a quick response. I am able to make it work with the suggested changes.
Much appreciated!
